###########
# site.title

title:    'Mob Eraser'
subtitle: 'Removing Villagers from Images in Minecraft'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
