###########
# site.title

title:    'Tourist Eraser'
subtitle: 'Removing Mobs From Images in Minecraft'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
